spring:
  datasource:
    jdbcurl: jdbc:postgresql://localhost:5432/loandev
    username: postgres
    password: mysecretp@ssword
    pool-size: 30
  jpa:
    hibernate:
      ddlAuto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
      namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
      show-sql: true
      use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type: trace
flyway:
  url: jdbc:postgresql://localhost:5432/loandev
  user: "postgres"
  password: "mysecretp@ssword"
  pool-size: 30
  baseline-on-migrate: true