#spring:
#  datasource:
#    jdbc-url: jdbc:postgresql://localhost:5432/loandev
#    username: postgres
#    password: mysecretp@ssword
#    pool-size: 30
#  jpa:
#    hibernate:
#      ddlAuto: validate
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
#      show-sql: true
#use_sql_comments: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#flyway:
#  url: jdbc:postgresql://localhost:5432/loandev
#  user: "postgres"
#  password: "mysecretp@ssword"
#  pool-size: 30
#  baseline-on-migrate: true
spring:
  datasource:
    jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      driverClassName: org.h2.Driver
      dialect: org.hibernate.dialect.H2Dialect
      ddlAuto: create-drop
      show-sql: true
      use_sql_comments: true
      format_sql: true
  flyway:
    enabled: false
logging:
  level:
    org:
      hibernate:
        type: trace